### ISSUE TITLE
Syntax for structure 

### ISSUE THREAD

**Issue by Rachel10011** [Gabeele/Blackjack#1]
https://github.com/Gabeele/Blackjack/blob/967b486388338f645f39cda3bac8b46fbb154cd6/CSCN71030_W21_Blackjack_Group5/GUI.c#L27
I used PLAYERLIST* instead of pPLAYERLIST and I used  PLAYER instead pPLAYER.

**Comment by Gabeele** [comment]
Hi Rachel, I tend to use pointers instead of direct reference (-> instead of .) for almost everything outside of its original module. Would you be okay with switching to pPlayer syntax?

**Comment by Rachel10011** [comment]
Sure, I'll add and change them in my module.
