### ISSUE TITLE
'Getter' Functions Needed

### ISSUE THREAD

**Issue by Gabeele** [Gabeele/Blackjack#10]
https://github.com/Gabeele/Blackjack/blob/18f85744d9676d8fc095680f14b88b2a295249a9/CSCN71030_W21_Blackjack_Group5/GUI.c#L31

Hi Rachel, 

Because of the use of pointers, we might need a few getter functions that would just return the player, name, etc. They won't be complicated and would just return what is needed. 

getPlayer -takes in a pNode and returns the pPLayer
getName - Takes in a pPlayer and returns a string 
getBalance - takes in a pPlayer and returns the balance 

I think that is it.

**Comment by Rachel10011** [comment]
get functions are added now

**Comment by Gabeele** [comment]
Thank you!
