### ISSUE TITLE
Mallocing error checking

### ISSUE THREAD

**Issue by Gabeele** [Gabeele/Blackjack#11]
https://github.com/Gabeele/Blackjack/blob/9f4a47267baa182b33dd3ab6d7dd9f7afbba4c81/CSCN71030_W21_Blackjack_Group5/Player.cpp#L5

We should also include a quick if statement to allow error checking of all the mallocs. 

If(Node = null){
"error allocating data"
exit(0)
} 

Something like this would be great!

**Comment by Rachel10011** [comment]
it is now added

**Comment by Gabeele** [comment]
Thanks Rachel!
