### ISSUE TITLE
Taking in abort value as an int.

### ISSUE THREAD

**Issue by JessVuksic** [Gabeele/Blackjack#18]
https://github.com/Gabeele/Blackjack/blob/8d3b89a2a0fbc5cb2cec8deabc4cc5c8b7477828/CSCN71030_W21_Blackjack_Group5/GUI.c#L306

Currently in your code when taking in input from the player you take it in as an int, since our abort value is 0000 due to being cast as an int it will just narrow down to 0 and no longer be the abort value.

**Comment by Gabeele** [comment]
Thanks josh, fixed in the master branch.
