### ISSUE TITLE
Input Validation not checking abort value in case of valid integers. 

### ISSUE THREAD

**Issue by JessVuksic** [Gabeele/Blackjack#22]
https://github.com/Gabeele/Blackjack/blob/0ea03f5eba7b739823c6a6e87b16fe10a253e68f/CSCN71030_W21_Blackjack_Group5/inputValidation.c#L22

The input validation only checks whether given input is the abort value if the input is considered an invalid integer. The root cause of this is that the check abort if under the wrong else/if statement. This was found while testing input "0000". Also in the GUI it is inefficient to repeatedly call checkInt instead of just calling it once.

**Comment by Gabeele** [comment]
Thanks Josh. We altered the values of the check abort if statements to reflect what our plan was. Re testing and everything was working great now!

**Comment by Gabeele** [comment]
As for the ineffectiveness, I created a variable that calls the check function once rather than the multiple times. IT will be pushed in the newest version.
