### ISSUE TITLE
Missing function.

### ISSUE THREAD

**Issue by JessVuksic** [Gabeele/Blackjack#24]
https://github.com/Gabeele/Blackjack/blob/daed3b350d6c6a90906b160e7af21c03a57cb454/CSCN71030_W21_Blackjack_Group5/GUI.c#L54

Player.c is missing one of the functions called upon by the GUI. we discovered this during integration testing between the two modules. The solution will be to create the missing function.

**Comment by Gabeele** [comment]
Created the getPlayerListFunction in the player module to assist in the transaction we need.

**Comment by Gabeele** [comment]
Will be in the next commit pushed
