### ISSUE TITLE
Create player is being called upon with invalid input.

### ISSUE THREAD

**Issue by JessVuksic** [Gabeele/Blackjack#25]
https://github.com/Gabeele/Blackjack/blob/fd609682b1e115a2e7833e5dc042ff32b0054d51/CSCN71030_W21_Blackjack_Group5/GUI.c#L195

Only a name should be passed, while currently a player and playerlist are being passed.

**Comment by Gabeele** [comment]
Yeah thank you. Fixed in the new version of file IO.
