### ISSUE TITLE
Creation of an infinite loop.

### ISSUE THREAD

**Issue by JessVuksic** [Gabeele/Blackjack#27]
https://github.com/Gabeele/Blackjack/blob/0e99e80c5aa0ebbab87a65f67d127176233c2004/CSCN71030_W21_Blackjack_Group5/GUI.c#L32

When running this with the player it seems to create an infinite loop. Found while integration testing.

**Comment by Gabeele** [comment]
Fixed by including 
		`node = node->nextPlayer;`
on line 173. The issue was the node was not being moved forward.

**Comment by Gabeele** [comment]
Will fix in the next commit release
.
