### ISSUE TITLE
Selecting a player does not select the correct player

### ISSUE THREAD

**Issue by JessVuksic** [Gabeele/Blackjack#28]
https://github.com/Gabeele/Blackjack/blob/0e99e80c5aa0ebbab87a65f67d127176233c2004/CSCN71030_W21_Blackjack_Group5/GUI.c#L36

When trying to select a player no matter what it will select player one. Discovered while trying to select player 2 during integration testing.

**Comment by Gabeele** [comment]
Hi, thank you. I made a similar mistake using node->next instead of node - node->next. All fixed and will push now!
