### ISSUE TITLE
Saving to file and reading to file issue

### ISSUE THREAD

**Issue by Gabeele** [Gabeele/Blackjack#33]
Test case 0009. 

I ran the test to check on the writing to a file with the read in data. Looks like the data saved got corrupted and different text got saved. In the process, I did not alter the data in any way. The steps I took was: run the program, selected josh, clicked 0 to exit, and then reopen the program, the player menu select printed to display not expected data. 

![image](https://user-images.githubusercontent.com/59030389/114433233-95283180-9b8f-11eb-966f-0be4f59182d5.png)

I will investigate further, but I am not sure what is issue would be. Possibly out encryption.

**Comment by Gabeele** [comment]
I think it might have something to do with the - when encryping, something to take note of.

**Comment by JessVuksic** [comment]
I looked into it and found that the issues occurred upon moving to the next player I was moving the head instead of moving the data from the head leading to it reading some weird stuff it has been fixed now and is working as it should.
