### ISSUE TITLE
Refill balance did not prompt user

### ISSUE THREAD

**Issue by ghost** [Gabeele/Blackjack#35]
Test case ID: 0015

The issue occurs in this function:
https://github.com/Gabeele/Blackjack/blob/ea99a06debae7c26e0ae8d289d7bdd6779e782fa/CSCN71030_W21_Blackjack_Group5/GUI.c#L262

The function should prompt the user. To investigate this issue, further analyzation of the function is required.

**Comment by Gabeele** [comment]
Hi Colin, thanks for the heads up. Looks like when I programmed the GUI I used the wrong function to reset the balance. It is changed to the correct one and retested. 

 You will find the new version in commit  6dc67e4f.
