### ISSUE TITLE
There is not an option to create a new player

### ISSUE THREAD

**Issue by ghost** [Gabeele/Blackjack#36]
Test Case ID: 0021

The issue is in this function:
https://github.com/Gabeele/Blackjack/blob/ea99a06debae7c26e0ae8d289d7bdd6779e782fa/CSCN71030_W21_Blackjack_Group5/GUI.c#L16

There is no way to add a player when a player list is initialized.

**Comment by Gabeele** [comment]
I apologize for that mistake. I am working on it now.

**Comment by Gabeele** [comment]
Added the functionality in to GUI.c. tested it out on my own, everything looks good. 

Will be pushed on commit aa1c78e0.
