### ISSUE TITLE
Exepction gets called on the balance

### ISSUE THREAD

**Issue by Gabeele** [Gabeele/Blackjack#39]
https://github.com/Gabeele/Blackjack/blob/8c4ffa64226339ff23629acf47648c68e55aa0a4/CSCN71030_W21_Blackjack_Group5/GameMechanics.c#L181

When going through the code via a breakpoints, we can see the int* balance is pointing to nothing in memory. It happens when determineWinner function is called in the playRound function. 

We should look for a solution and push this in a new release.

**Comment by ghost** [comment]
Thanks. The issue was in the determine winner function call, it was passed a value instead of a pointer address.

This is the Commit id: 747cf00
I will commit and push the changes into the new release!
