### ISSUE TITLE
Functions need in player

### ISSUE THREAD

**Issue by Gabeele** [Gabeele/Blackjack#4]
https://github.com/Gabeele/Blackjack/blob/967b486388338f645f39cda3bac8b46fbb154cd6/CSCN71030_W21_Blackjack_Group5/GUI.c#L50

Around this area in my code I have two functions 
		playerListLength(playerList) 
		getPlayerFromList(playerList, playerIndex) 
where the player list is the playerList pointer and player index would be the number entered in by the user to select the player. Now this number would be sort of like the index of an array. 

For the getPlayerFromList:
If you have 5 members in the list, the user chooses the second one, it would be the second person from the head. I was wondering if you could also include a function for this in the player module. 

For the playerListLength:
Would just return the total length or items in the list.

**Comment by Rachel10011** [comment]
Sure, I'll add them to my module

**Comment by Gabeele** [comment]
Thank you!
