### ISSUE TITLE
Parameters in the CheckInt Function

### ISSUE THREAD

**Issue by Gabeele** [Gabeele/Blackjack#5]
https://github.com/Gabeele/Blackjack/blob/d569ad958057cd56e69aa753149468b81eaa6bf7/CSCN71030_W21_Blackjack_Group5/Source.c#L11

Hi! Are the parameters supposed to be a char array? I figured it would be just a simple int?

**Comment by JessVuksic** [comment]
when checking input if the variable has been stored in an int it will only take an int so if someone was to type 12sd it would only take the 12 or just sd it would take zero leaving. The biggest problem with this is that if we store it as an int and they want to enter our abort value or 0000 it wont take as in an int that is just a 0.

**Comment by Gabeele** [comment]
Sounds good. I figure it could also be that way. Good thinking!
