### ISSUE TITLE
Scanf_S in Game Mechanics

### ISSUE THREAD

**Issue by Gabeele** [Gabeele/Blackjack#6]
https://github.com/Gabeele/Blackjack/blob/7c1a6cb5a0c164654326e5fa38d30963c6d8d4a3/CSCN71030_W21_Blackjack_Group5/GUI.c#L284

Hi! 

We discussed about other ways to interface with the user through the GUI. We decided on the getInput function to do this, that way you can ask for input and it will do all the necessary checks.

**Comment by ghost** [comment]
Completed.
