### ISSUE TITLE
Source file 

### ISSUE THREAD

**Issue by Gabeele** [Gabeele/Blackjack#8]
https://github.com/Gabeele/Blackjack/blob/bc0e1fca9a008cf0ef0be5dd18d4e452e6a8455d/CSCN71030_W21_Blackjack_Group5/Source.c#L1

Just a simple issue, looks like the code is in your source file, possibly just copy paste into a separate FileIO.c file.

**Comment by JessVuksic** [comment]
I have changed the name in both file/IO and input validation, thank you for bringing this to my attention.

**Comment by Gabeele** [comment]
Sounds great Josh, thank you!
