### ISSUE TITLE
player.cpp File Type

### ISSUE THREAD

**Issue by Gabeele** [Gabeele/Blackjack#9]
https://github.com/Gabeele/Blackjack/blob/9f4a47267baa182b33dd3ab6d7dd9f7afbba4c81/CSCN71030_W21_Blackjack_Group5/Player.cpp#L2

Hi! I just saw that the file type is a .cpp when we are actually coding in c. I think you might be able to change the file extension or you might just have to copy paste into a new file as player.c

**Comment by Rachel10011** [comment]
Thanks for noticing me

**Comment by Gabeele** [comment]
Perfect, I see you made the new changes.
